### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MiroslavHustak**
**Problem: ProgressBar determinate**

_Solution ElmishWPF (not-yet finished conversion from FsXaml/Code Behind)_
It is a single-window app. No tabs. Here, the ProgressBar determinate controls work - see the question and answer here: [https://stackoverflow.com/questions/70208381/updating-progressbar-value-in-fsxaml-and-elmishwpf](url)

_Solution ElmishWPFx (not-yet finished conversion from FsXaml/Code Behind)_
It is an app with one main window and tabs. The code is based on the following example codes by Bent Tranberg:

1. [ElmishXmas](https://github.com/BentTranberg/ElmishXmas)
2. [ExploreElmishWpf]( https://github.com/BentTranberg/ExploreElmishWpf)
3. Relevant async code in ElmishWPF 
4. [https://stackoverflow.com/questions/70208381/updating-progressbar-value-in-fsxaml-and-elmishwpf](url)

**Here, the ProgressBar determinate controls do not work**.   The commands  _Cmd.OfAsync.either asyncOperationGoogle () (FinishAsync >> GoogleButtonEvent) (FailAsync >> GoogleButtonEvent)_ in LeftCalc.fs (or  _Cmd.OfAsync.either asyncOperationSynology (m: Model) (FinishAsync >> SynologyButtonEvent) (FailAsync >> SynologyButtonEvent)_ in RightCalc.fs respectively) are not fired. Also the functions _delayedCmd (dispatch: Msg -> unit): unit_ in both fs files do not fire either. _Async_ is what they all have in common.

See the relevant code:

File: MainWindow.fs

`
namespace ElmishWPFx.Models

module MainWindow =

    open System
    open System.Windows
    open System.Windows.Media
    open Elmish
    open Elmish.WPF
    open ElmishWPF.Models

    open Serilog
    open Serilog.Extensions.Logging

    let newGuid () = Guid.NewGuid()

    type Toolbutton =
        {
            Id: Guid
            Text: string
            IsMarkable: bool
        }

    type Tab =
        {
            Id: Guid
            Header: string
            Toolbuttons: Toolbutton list
        }

    type Msg =
        | ButtonClick of id: Guid
        | ShowLeftCalc
        | ShowRightCalc
        | ShowSettings
        | ShowLicences
        | LeftCalcMsg of LeftCalc.Msg
        | RightCalcMsg of RightCalc.Msg
        | SettingsMsg of Settings.Msg
        | LicencesMsg of Licences.Msg

    type Model =
        {
            Tabs: Tab list
            MarkedButton: Guid
            LeftCalcPage: LeftCalc.Model option
            RightCalcPage: RightCalc.Model option
            SettingsPage: Settings.Model option
            LicencesPage: Licences.Model option
        }
        with
            member x.somePageIsVisible =
                x.LeftCalcPage.IsSome || x.RightCalcPage.IsSome || x.SettingsPage.IsSome || x.LicencesPage.IsSome

    let tbNone = newGuid ()
    let tbLeftCalc = newGuid ()
    let tbRightCalc = newGuid ()
    let tbSettings = newGuid ()
    let tbLicences = newGuid ()  

    let tabs =
        let tab header toolButtons =
            { Id = newGuid (); Header = header; Toolbuttons = toolButtons }
        let toolbutton id text isMarkable =
            { Id = id; Text = text; IsMarkable = isMarkable }
        let firstTab =
            [
              toolbutton tbLeftCalc "Left Calculation" true
              toolbutton tbRightCalc "Right Calculation" true         
            ]
        let secondTab = 
            [      
              toolbutton tbSettings "Settings Page" true
              toolbutton tbLicences "Licences" true      
            ]
        [ tab "Calculations" firstTab; tab "Settings" secondTab ]

    let startModel =
        {
            Tabs = tabs
            MarkedButton = tbLeftCalc
            LeftCalcPage = None
            RightCalcPage = None               
            SettingsPage = None
            LicencesPage = None
        }

    let init () = startModel, Cmd.ofMsg ShowLeftCalc

    let findButton (id: Guid) (m: Model) =
        m.Tabs |> List.tryPick (fun tab -> tab.Toolbuttons |> List.tryFind (fun tb -> tb.Id = id))

    let update msg m =
        match msg with
        | ButtonClick id ->
            match findButton id m with
            | None -> m, Cmd.none
            | Some clickedButton ->
                let m = if clickedButton.IsMarkable then { m with MarkedButton = id } else m
                if clickedButton.Id = tbLeftCalc then m, Cmd.ofMsg ShowLeftCalc
                elif clickedButton.Id = tbRightCalc then m, Cmd.ofMsg ShowRightCalc  
                elif clickedButton.Id = tbSettings then m, Cmd.ofMsg ShowSettings
                elif clickedButton.Id = tbLicences then m, Cmd.ofMsg ShowLicences
                else m, Cmd.none

        | ShowLeftCalc ->
            match m.LeftCalcPage with
            | None -> { m with LeftCalcPage = fst (LeftCalc.init()) |> Some }, Cmd.none
            | Some _ -> m, Cmd.none
        | ShowRightCalc ->
            match m.RightCalcPage with
            | None -> { m with RightCalcPage = fst (RightCalc.init()) |> Some }, Cmd.none
            | Some _ -> m, Cmd.none      
        | ShowSettings->
            match m.SettingsPage with
            | None -> { m with SettingsPage = Settings.init () |> Some }, Cmd.none
            | Some _ -> m, Cmd.none
        | ShowLicences ->
            match m.LicencesPage with
            | None -> { m with LicencesPage = Licences.init |> Some }, Cmd.none
            | Some _ -> m, Cmd.none
        | LeftCalcMsg msg' ->
            match m.LeftCalcPage with
            | None -> m, Cmd.none
            | Some m' -> LeftCalc.update msg' m' |> (fun m' -> { m with LeftCalcPage = Some (fst m') }, Cmd.none)
        | RightCalcMsg msg' ->
            match m.RightCalcPage with
            | None -> m, Cmd.none
            | Some m' -> RightCalc.update msg' m' |> (fun m' -> { m with RightCalcPage = Some (fst m') }, Cmd.none)  
        | SettingsMsg msg' ->
            match m.SettingsPage with
            | None -> m, Cmd.none
            | Some m' -> Settings.update msg' m' |> (fun m' -> { m with SettingsPage = Some m' }, Cmd.none)
        | LicencesMsg msg' ->
            match m.LicencesPage with
            | None -> m, Cmd.none
            | Some m' -> Licences.update msg' m' |> (fun m' -> { m with LicencesPage = Some m' }, Cmd.none) 

    let bindings(): Binding<Model,Msg> list =
        [
            "Tabs" |> Binding.subModelSeq((fun m -> m.Tabs), (fun t -> t), fun () ->
                [
                    "Id" |> Binding.oneWay (fun (_, t) -> t.Id)
                    "Header" |> Binding.oneWay (fun (_, t) -> t.Header)
                    "Toolbuttons" |> Binding.subModelSeq((fun (_, t) -> t.Toolbuttons), (fun t -> t), fun () ->
                        [
                            "Id" |> Binding.oneWay (fun (_, t) -> t.Id)
                            "Text" |> Binding.oneWay (fun (_, t) -> t.Text)
                            // "ImageSource" |> Binding.oneWay (fun (_, t) -> t.ImageSource)
                            "Foreground" |> Binding.oneWay (fun (_, t) -> Brushes.Green)
                            "ButtonClick" |> Binding.cmd (fun (_, (t: Toolbutton)) -> ButtonClick t.Id)
                            "MarkerVisible" |> Binding.oneWay (fun ((m, tab), tb) -> tb.Id = m.MarkedButton && m.somePageIsVisible)
                        ])
                ])
            "LeftCalcPage"  |> Binding.subModelOpt ((fun (m: Model) -> m.LeftCalcPage), snd, LeftCalcMsg, LeftCalc.bindings)
            "RightCalcPage" |> Binding.subModelOpt ((fun (m: Model) -> m.RightCalcPage), snd, RightCalcMsg, RightCalc.bindings)       
            "SettingsPage"  |> Binding.subModelOpt ((fun (m: Model) -> m.SettingsPage), snd, SettingsMsg, Settings.bindings)
            "LicencesPage"  |> Binding.subModelOpt ((fun (m: Model) -> m.LicencesPage), snd, LicencesMsg, Licences.bindings)

            "LeftCalcPageVisible"  |> Binding.oneWay (fun m -> m.MarkedButton = tbLeftCalc && m.LeftCalcPage.IsSome)
            "RightCalcPageVisible" |> Binding.oneWay (fun m -> m.MarkedButton = tbRightCalc && m.RightCalcPage.IsSome)
            "SettingsPageVisible"  |> Binding.oneWay (fun m -> m.MarkedButton = tbSettings && m.SettingsPage.IsSome)
            "LicencesPageVisible"  |> Binding.oneWay (fun m -> m.MarkedButton = tbLicences && m.LicencesPage.IsSome)           
        ]
    
    let designTimeModel = ViewModel.designInstance startModel (bindings())
   
            `
File: LeftCalc.fs
`
namespace ElmishWPFx.Models

module LeftCalc =

    open System

    open Elmish
    open Elmish.WPF

    open MainLogicLeft
    open Elmish.Support

    open FSharp.Control
    open System.Windows.Media    

    type ProgressIndicator = Idle | InProgress of percent: int

    type Model =
        {
            MainTextBoxText: string           
            ProgressIndeterminateLeft: bool
            ProgressBackgroundLeft: Brush
            ProgressIndicatorLeft: ProgressIndicator
        }

    let initialModel = 
        {
            MainTextBoxText = String.Empty
            ProgressIndeterminateLeft = false
            ProgressBackgroundLeft = Brushes.LightSkyBlue
            ProgressIndicatorLeft = Idle
        }

    let init() = initialModel, Cmd.none
        
    type Msg =
        | NumberOfImagesButtonEvent  
        | GoogleButtonEvent of Aos<unit, Result<string, string>, exn>
        | UpdateStatusLeft of progress: int
        | WorkIsCompleteLeft
        | TestButtonLeftEvent   

    //**********************************************************************************************************************************
    // FOR TESTING PURPOSES ONLY 
    let private workToDoLeft dispatch = 
       async
           {
               for i in 1..100 do 
                   do! Async.Sleep 20  //simulating long running operation
                   dispatch (UpdateStatusLeft i) 
               dispatch WorkIsCompleteLeft 
            } 

    //**********************************************************************************************************************************

    //************************* Google ******************************
    let private msgGoogleButtonEvent = GoogleButtonEvent(StartAsync()) 

    let private asyncOperationGoogle(): Async<Result<string,string>> = 
        async 
           {
               let! result = async { return textBoxString2() } 
               return Result.Ok result
           }

    let private googleButtonEvent event (m: Model) =
        match event with
        | StartAsync () ->
            { m with MainTextBoxText = "Údaje se posílají do Google Sheets tabulky ..." 
                     ProgressIndeterminateLeft = true
                     ProgressBackgroundLeft = Brushes.White
            }, Cmd.OfAsync.either asyncOperationGoogle () (FinishAsync >> GoogleButtonEvent) (FailAsync >> GoogleButtonEvent) //vsimni si parametru asyncOperation a te mezery u () 
        | FinishAsync (Result.Ok value) ->
            { m with MainTextBoxText = value
                     ProgressIndeterminateLeft = false
                     ProgressBackgroundLeft = Brushes.LightSkyBlue
            }, Cmd.none
        | FinishAsync (Result.Error error) ->
            { m with MainTextBoxText = $"Done, but with error {error}" 
                     ProgressIndeterminateLeft = false
                     ProgressBackgroundLeft = Brushes.LightSkyBlue
            }, Cmd.none
        | FailAsync (ex: exn) ->
            { m with MainTextBoxText = $"Done, but with exception message {ex.Message}" 
                     ProgressIndeterminateLeft = false
                     ProgressBackgroundLeft = Brushes.LightSkyBlue
            }, Cmd.none

    let update (msg: Msg) (m: Model) : Model * Cmd<Msg> = 
        match msg with  
        | NumberOfImagesButtonEvent  -> { m with MainTextBoxText = textBoxString1() }, Cmd.none  
        | GoogleButtonEvent event    -> googleButtonEvent event m //Only for ProgressBar Indeterminate (left)        
        | UpdateStatusLeft progress  -> { m with MainTextBoxText = "ProgressBar test running ..."; ProgressIndicatorLeft = InProgress progress; ProgressBackgroundLeft = Brushes.White }, Cmd.none                      
        | WorkIsCompleteLeft         -> { m with ProgressIndicatorLeft = Idle; ProgressBackgroundLeft = Brushes.LightSkyBlue; MainTextBoxText = "End of ProgressBar test"; }, Cmd.none            
        | TestButtonLeftEvent        -> let delayedCmd (dispatch: Msg -> unit) : unit =  
                                            let delayedDispatch = workToDoLeft dispatch //test case only, no need for a determinate ProgressBar (left) in this app 
                                            Async.StartImmediate delayedDispatch 
                                        { m with ProgressIndicatorLeft = InProgress 0 }, Cmd.ofSub delayedCmd                                           
   
    //cmdIf disables the relevant button, cmd does not
    let bindings(): Binding<Model,Msg> list =
        [
          "MainTextBoxText"      |> Binding.oneWay(fun m -> m.MainTextBoxText)
          "NumberOfImagesButton" |> Binding.cmd NumberOfImagesButtonEvent  
          "GoogleButton"         |> Binding.cmd msgGoogleButtonEvent    //Only for ProgressBar Indeterminate (left)  
          "ProgressLeftIndeter"  |> Binding.oneWay(fun m -> m.ProgressIndeterminateLeft)           
          "ProgressLeftBackg"    |> Binding.oneWay(fun m -> m.ProgressBackgroundLeft) 
          "ProgressLeft"         |> Binding.oneWay(fun m -> match m.ProgressIndicatorLeft with Idle -> 0.0 | InProgress v -> float v)
          "TestButtonLeft"       |> Binding.cmdIf(TestButtonLeftEvent, fun m -> match m.ProgressIndicatorLeft with Idle -> true | _ -> false)    //test case
        ]

    let designVm = ViewModel.designInstance initialModel (bindings()) 
`

File: RightCalc.fs
`
namespace ElmishWPFx.Models

module RightCalc =

    open System

    open Elmish
    open Elmish.WPF

    open MainLogicRight
    open Elmish.Support

    open FSharp.Control
    open System.Windows.Media
    
    type ProgressIndicator = Idle | InProgress of percent: int
    
    type Model =
        {
            MainTextBoxText: string
            LowLimit: string
            HighLimit: string
            PathToSynology: string
            ProgressIndeterminateRight: bool
            ProgressBackgroundRight: Brush
            ProgressIndicatorRight: ProgressIndicator    
        }
    
    let initialModel = 
        {
            MainTextBoxText = String.Empty
            LowLimit = String.Empty
            HighLimit = String.Empty
            PathToSynology = String.Empty
            ProgressIndeterminateRight = false
            ProgressBackgroundRight = Brushes.LightSkyBlue
            ProgressIndicatorRight = Idle
        }
    
    let init() = initialModel, Cmd.none
            
    type Msg =
        | SynologyButtonEvent of Aos<unit, Result<string, string>, exn>
        | LowLimitChanged of string
        | HighLimitChanged of string
        | PathToSynologyChanged of string
        | UpdateStatusRight of progress:int
        | WorkIsCompleteRight of string
        | TestButtonRightEvent     
    
    //************************ Synology *****************************
    let private msgSynologyButtonEvent = SynologyButtonEvent(StartAsync()) 
    
    let private mainLogicRight low high path =     
        let result4 = textBoxString4 low high 
        let result3 =
            let reportProgress progressValue = () //dummy partial app fn
            textBoxString3 low high path reportProgress
        match result4 >= 0 with
        | false -> result3
        | true  -> "Chybný rozdíl limitních hodnot anebo limity nebyly vůbec zadány" 
     
    let private asyncOperationSynology(m: Model): Async<Result<string,string>> = 
        async 
           {
               let! result = async { return mainLogicRight m.LowLimit m.HighLimit m.PathToSynology } 
               return Result.Ok result
           }
      
    let private synologyButtonEvent event (m: Model) =
        match event with
        | StartAsync () ->
            { m with MainTextBoxText = "Příslušné hodnoty se načítají a zpracovávají ..." 
                     ProgressIndeterminateRight = true
                     ProgressBackgroundRight = Brushes.White
            }, Cmd.OfAsync.either asyncOperationSynology (m: Model) (FinishAsync >> SynologyButtonEvent) (FailAsync >> SynologyButtonEvent) //vsimni si parametru asyncOperation a te mezery u () 
        | FinishAsync (Result.Ok value) ->
            { m with MainTextBoxText = value
                     ProgressIndeterminateRight = false
                     ProgressBackgroundRight = Brushes.LightSkyBlue
            }, Cmd.none
        | FinishAsync (Result.Error error) ->
            { m with MainTextBoxText = $"Done, but with error {error}" 
                     ProgressIndeterminateRight = false
                     ProgressBackgroundRight = Brushes.LightSkyBlue
            }, Cmd.none
        | FailAsync (ex: exn) ->
            { m with MainTextBoxText = $"Done, but with exception message {ex.Message}" 
                     ProgressIndeterminateRight = false
                     ProgressBackgroundRight = Brushes.LightSkyBlue
            }, Cmd.none
    
    let update (msg: Msg) (m: Model) : Model * Cmd<Msg> = 
        match msg with  
        | SynologyButtonEvent event  -> synologyButtonEvent event m //Only for ProgressBar Indeterminate (right)                             
        | LowLimitChanged low        -> { m with LowLimit = low }, Cmd.none
        | HighLimitChanged high      -> { m with HighLimit = high }, Cmd.none
        | PathToSynologyChanged path -> { m with PathToSynology = path }, Cmd.none// -> { m with PathToSynology =  @"o:\Litoměřice 8. část\" }, Cmd.none
        | UpdateStatusRight progress -> { m with MainTextBoxText = "Příslušné hodnoty se načítají a zpracovávají ..."; ProgressIndicatorRight = InProgress progress; ProgressBackgroundRight = Brushes.White }, Cmd.none 
        | WorkIsCompleteRight result -> { m with ProgressIndicatorRight = Idle; ProgressBackgroundRight = Brushes.LightSkyBlue; MainTextBoxText = result; ProgressIndeterminateRight = false }, Cmd.none 
        | TestButtonRightEvent       -> let delayedCmd (dispatch: Msg -> unit): unit =       
                                            let delayedDispatch: Async<unit> = 
                                                async
                                                   {
                                                       let reportProgress progressValue = dispatch (UpdateStatusRight progressValue)
                                                       let result4 = textBoxString4 m.LowLimit m.HighLimit  
                                                       //let! hardWork = Async.StartChild (workToDoRight reportProgress) //test case
                                                       let! hardWork = Async.StartChild (async { return textBoxString3 m.LowLimit m.HighLimit m.PathToSynology reportProgress }) //real-life case
                                                       //do! Async.Sleep 1000 // Can do some async work here too while waiting for hardWork to finish.
                                                       let! result3 = hardWork 
                                                       let result = 
                                                           match result4 >= 0 with
                                                           | false -> result3
                                                           | true  -> "Chybný rozdíl limitních hodnot anebo limity nebyly vůbec zadány"
                                                       dispatch (WorkIsCompleteRight result)
                                                   }                                       
                                            Async.StartImmediate delayedDispatch
                                        { m with ProgressIndicatorRight = InProgress 0; ProgressIndeterminateRight = true }, Cmd.ofSub delayedCmd                                     
       
    //cmdIf disables the relevant button, cmd does not
    let bindings(): Binding<Model,Msg> list =
        [
          "MainTextBoxText"      |> Binding.oneWay(fun m -> m.MainTextBoxText)
          "SynologyButton"       |> Binding.cmd msgSynologyButtonEvent  //Only for ProgressBar Indeterminate (right) 
          "LowLimit"             |> Binding.twoWay((fun m -> m.LowLimit), (fun newVal -> newVal |> LowLimitChanged))
          "HighLimit"            |> Binding.twoWay((fun m -> m.HighLimit), (fun newVal -> newVal |> HighLimitChanged))
          "PathToSynology"       |> Binding.twoWay((fun m -> m.PathToSynology), (fun newVal -> newVal |> PathToSynologyChanged))
          "ProgressRightIndeter" |> Binding.oneWay(fun m -> m.ProgressIndeterminateRight)  
          "ProgressRightBackg"   |> Binding.oneWay(fun m -> m.ProgressBackgroundRight) 
          "ProgressRight"        |> Binding.oneWay(fun m -> match m.ProgressIndicatorRight with Idle -> 0.0 | InProgress v -> float v)
          "TestButtonRight"      |> Binding.cmdIf(TestButtonRightEvent, fun m -> match m.ProgressIndicatorRight with Idle -> true | _ -> false)  //test case + real-life case
        ]
    
    let designTimeModel = //pouze pro XAML/Design v MainWindow.xaml
        {       
            MainTextBoxText = String.Empty
            LowLimit = String.Empty
            HighLimit = String.Empty
            PathToSynology = String.Empty
            ProgressIndeterminateRight = false
            ProgressBackgroundRight = Brushes.Yellow
            ProgressIndicatorRight = InProgress 50
        }
    
    //Data Context
    let designVm = ViewModel.designInstance designTimeModel (bindings())
    //let designVm = ViewModel.designInstance initialModel (bindings())`

### CODE REVIEW

**Comment by BentTranberg** [comment]
I found out that when I change `LeftCalcPage` from type `LeftCalc.Model option` into a `LeftCalc.Model` (no `option`), then it works as expected.

I don't know what the problem is, but anyhow I think it is better to just use submodels that are not optional in this case. Even if we do figure out exactly what is wrong, I think there is still a great risk that you will just run into more trouble later if optional models are used in this and similar cases. I believe optional models and asyncs are possibly a bad mix, unless we are very sure about exactly how messages are handled in every possible situation. I for one find that rather hard to understand. I am still going to use optional submodels in my projects in the way demonstrated in the **SubModelOpt** sample in Elmish.WPF. That means I will use it for simple dialogs that won't have any async stuff in them.

It is quite possible that some of our more advanced friends can have more enlightening advice on this matter just by looking at the source, now that we know a little bit more about the source of the problem, and perhaps even point to the exact problem. We could pursue the matter by raising an issue in the Elmish.WPF repository, if you really want to get to the bottom of this.

In order to investigate this, I created a rather minimal repro. This is the code with essential changes. It can be helpful if you do choose to just make this change away from optional models. Note that here I also demonstrate how to create submodel bindings in the new way, so that you won't get warnings about deprecated calls. Should you still use optional submodels somewhere, then the same can be done by replacing `Binding.SubModel.required` with `Binding.SubModel.opt`

```
type Msg =
    | LeftCalcMsg of LeftCalc.Msg

type Model =
    {
        LeftCalcPage: LeftCalc.Model
    }

let init () : Model * Cmd<Msg> =
    let leftCalcPage, leftCalcPageCmd = LeftCalc.init ()
    {
        LeftCalcPage = leftCalcPage
    }, Cmd.map LeftCalcMsg leftCalcPageCmd

let update msg m =
    match msg with
    | LeftCalcMsg msg' ->
        let m', cmd' = LeftCalc.update msg' m.LeftCalcPage
        { m with LeftCalcPage = m' }, Cmd.map LeftCalcMsg cmd'

let bindings(): Binding<Model,Msg> list = [
    // deprecated binding:
    // "LeftCalcPage" |> Binding.subModel ((fun (m: Model) -> m.LeftCalcPage), snd, LeftCalcMsg, LeftCalc.bindings)

    // new binding:
    "LeftCalcPage"
        |> Binding.SubModel.required LeftCalc.bindings
        |> Binding.mapModel (fun m -> m.LeftCalcPage)
        |> Binding.mapMsg LeftCalcMsg
    ]

let designTimeModel = ViewModel.designInstance (fst (init ())) (bindings())
```

**Comment by BentTranberg** [comment]
I just found out that I am already using many optional models in my projects, and most of them works well with lots of async stuff without any problems. There must be something that I haven't yet spotted in the minimal reproducible sample that I've made from your code. I will continue to investigate.

But I am still of the opinion that non-optional models are better in your case. In my programs I use optional models in cases where it is advantageous that a great number of models are not loaded all at the same time when the program starts, but rather are loaded the first time the user selects a tab/page.

**Comment by BentTranberg** [comment]
I have finally discovered the actual problem. I guess I should have spotted that right away, but I think I was thrown off track by a slightly confusing naming of a value. I assume the same problem is present in at least two and probably all your optional submodels, so let me know if there are still problems when you have applied the following fix wherever needed.

The original code, in just one of the places.

```
    | LeftCalcMsg msg' ->
        match m.LeftCalcPage with
        | None -> m, Cmd.none
        | Some m' -> LeftCalc.update msg' m' |> (fun m' -> { m with LeftCalcPage = Some (fst m') }, Cmd.none)
```

The problem here is that the update is called, but the two tupled results are not both passed on. More specifically, the message from the update is not passed on. In `fun m'`, the `m'` is actually not a model, but a tuple with model and message. You can see that later on the same line, where `fst 'm` is used to get at the actual model inside the tuple `m'`.

I am rewriting the code for clarity and fixing the problem at the same time here.

```
    | LeftCalcMsg msg' ->
        match m.LeftCalcPage with
        | None -> m, Cmd.none
        | Some m' ->
            let m'', msg'' = LeftCalc.update msg' m'
            { m with LeftCalcPage = Some m'' }, Cmd.map LeftCalcMsg msg''
```

So now the incoming submodel and submessage is named `m'` and `msg'`, and the outgoing submodel and submessage is named `m''` and `msg''`. This makes it more clear which is which. The outgoing message `msg''` is now correctly passed on with `Cmd.map LeftCalcMsg msg''`

Even after this, I still believe non-sub models may be better for your case, but at least now we know optional submodels also work fine.

**Comment by BentTranberg** [comment]
I think we should stop commenting and editing in that old question on StackOverflow, or else we'll get unpopular. By all means post new questions on SO or Elmish.WPF here on GitHub (there you'll really get attention from experts far better than me) or F# Slack or your own repo(s) here.

**Comment by MiroslavHustak** [comment]
**1) Optional submodels**
Replacing my code with yours was enough. The commands in question (and the entire, although not-yet-finished app) **work properly now**. 

**2) Non-optional submodels that you have recommended**
When I was adapting my code according to your example, I ran into a problem of how to implement this part:
```
let init () : Model * Cmd<Msg> =
    let leftCalcPage, leftCalcPageCmd = LeftCalc.init ()
    {
        LeftCalcPage = leftCalcPage
    }, Cmd.map LeftCalcMsg leftCalcPageCmd
```
Finally, I ended with this:
```
    let leftCalcPage, leftCalcPageCmd = LeftCalc.init ()
    let rightCalcPage, (rightCalcPageCmd: Cmd<obj>) = RightCalc.init ()
    let settingsPage, (settingsPageCmd: Cmd<obj>) = Settings.init1 () //TODO (not finished yet)
    let licencesPage, (licencesPageCmd: Cmd<obj>) = Licences.init1 () //TODO (not finished yet)

    let startModel =
        {
            Tabs = tabs
            MarkedButton = tbLeftCalc           
            LeftCalcPage = leftCalcPage
            RightCalcPage = rightCalcPage               
            SettingsPage = settingsPage
            LicencesPage = licencesPage
        }

    let init () : Model * Cmd<Msg> = startModel, Cmd.map LeftCalcMsg leftCalcPageCmd
```
Now, the "non-optional app" **works properly**. Although I have no idea why _"Cmd\<obj>\"_ should be used (it is there because an exception message suggested putting it there).  

3) Aos (AsyncOperationStatus)

**Comment by MiroslavHustak** [comment]
Yes Bent, I agree. No more SO. I'll try to learn how to utilise GitHub properly.

Thank you very much for your kindness, patience and effort.

When I finish converting my app from FsXaml into Elmish.WPF (the settings tab), I'll upload the entire solution on GitHub.

Greetings, Mira

>
> I think we should stop commenting and editing in that old question on StackOverflow, or else we'll get unpopular. By all means >post new questions on SO or Elmish.WPF here on GitHub (there you'll really get attention from experts far better than me) or F# >Slack or your own repo(s) here.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.You are receiving this because you authored the thread.

-- 
My Business Website: http://hustak.somee.com, http://hustak.somee.com/Home/ReferencesEN
My Daughter's Art Website: http://natalie.somee.com
My YouTube Channel: https://www.youtube.com/user/ww123ification

**Comment by BentTranberg** [comment]
The `Settings `and `Licenses `are not declared with the expected signatures for `init `and `update`, like `LeftCalc `is.  That's why you ended up using `Cmd<obj>`. You are certainly going to need the proper signatures of `init `and `update `when you start to fill in the business logic there, so if you simply adjust the signatures right away to match that of `init `and `update `in `LeftCalc`, then it will all be good, and you can use the exact same logic for all in the main window.

The `RightCalc `looks like it has the exact same basic logic as `LeftCalc`, so I don't understand why you resorted to `Cmd<obj>` there. I suspect you might have missed a small detail somewhere.

It's very nice to see how well you're doing with Elmish.WPF. Hope you feel so far that it was well worth the effort to learn it and to use it. I think you've ended up with a far more robust program than if you had tried anything else, whether FsXaml or C#. We are of course not that many using Elmish.WPF compared to e.g. MVVM in C#, but we seem to have enough traction and followers to keep this going and growing quite far into the future. Elmish is very big, so even if WPF is replaced by new technologies, we'll still likely be able to just convert to some new desktop variant of Elmish. By the way, I use Bolero for web development, which is another Elmish based GUI framework. It's not the most popular F# web framework, but to me it seems the easiest to get started with.

**Comment by MiroslavHustak** [comment]
I was fiddling with Cmd<obj> for a little bit and here is what type appeared out of it: Cmd<page.Msg>
`   
    let leftCalcPage, (leftCalcPageCmd: Cmd<LeftCalc.Msg>) = LeftCalc.init () 

    let rightCalcPage, (rightCalcPageCmd: Cmd<RightCalc.Msg>) = RightCalc.init ()

    let settingsPage, (settingsPageCmd: Cmd<Settings.Msg>) = Settings.init1 () //TODO (not finished yet)

    let licencesPage, (licencesPageCmd: Cmd<Licences.Msg>) = Licences.init1 () //TODO (not finished yet)

    //Specifying the type with leftCalcPageCmdCmd was (and is) not necessary because the type is inferred from let init () : Model * Cmd<Msg> = startModel, Cmd.map LeftCalcMsg leftCalcPageCmd
`
Although I have no graphical skills, I am grateful for any programming job (because I am a relative newbie in programming), even those with front-end parts. And as an avid functional programmer since last March,  functional front-end skills will come in handy.  My respect to all those that do whatever useful to keep functional programming on track.

**Comment by BentTranberg** [comment]
Type inference is great, but I have found that it pays off to "anchor" the types in certain strategic places, instead of trying to use as much type inference as possible. Otherwise you run into the kind of problems you've experienced, when it can be very difficult to understand the origin of the type confusion.

When programming an Elmish.WPF application, I will typically make sure that both the `init` and the `update` functions are always firmly anchored down with full type annotations both for every single parameter as well as the return type. This is very easy to do, because they're usually the same in all models, and very simple. When this is done, then the type inference for pretty much all the other code will almost always work much more intelligently. That is, it will much more often agree with your own understanding of the code, which after all is precisely what you want from the type inference engine.

**Comment by MiroslavHustak** [comment]
The app has just been put on here: https://github.com/MiroslavHustak/ElmishWPFprogressBar .
There are still some unsolved issues with OnKeyDownHandler, Mouse.Enter and TextChanged events on the Settings page that I have not been able to deal with so far. But they are not relevant to the progress bar issue, so I'll start a new repository soon.

**Comment by BentTranberg** [comment]
Can't you just create issues in this repo if you have problems or questions? Go to the second tab above - Issues - to create an issue. I don't think it's effective to create a new repo for each question. I'm watching this repo, so hopefully I'll notice new issues soon enough, but you can also email me to alert me if you want me to look at an issue.

**Comment by MiroslavHustak** [comment]
Two issues created. One related to TextChanged, the other related to tabs. No more problems with OnKeyDownHandler and Mouse.Enter.

**Comment by BentTranberg** [comment]
I've been working this weekend, but will try to find some time to look at the issues this week.

**Pull request merged**
